# Generated by Django 5.1.4 on 2025-01-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0002_dutyorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dutyschedule',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='dutyschedule',
            name='is_holiday',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='dutyschedule',
            unique_together={('date', 'staff')},
        ),
    ]
