# Generated by Django 5.1.4 on 2025-01-14 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0003_alter_dutyschedule_options_dutyschedule_is_holiday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutySwapRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('accepted', '已接受'), ('rejected', '已拒绝'), ('cancelled', '已取消')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_sent', to='duty.staff')),
                ('requester_duty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_as_requester', to='duty.dutyschedule')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_received', to='duty.staff')),
                ('target_duty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_as_target', to='duty.dutyschedule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
